server:
   port: 8761

eureka:
   server:
       enableSelfPreservation: false  #关闭自我保护机制
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/