
spring:
  profiles:
    active: dev

mybatis:
   mapper-locations: classpath:mapping/*.xml
   type-aliases-package: com.soufang.model

#pagehelper
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql

#logger
Logger:
   level:
       com.soufang.mapper: info
