spring:
   application:
      name: core
   datasource:
      name: soufang
      url: jdbc:mysql://192.168.88.244:3306/yhkj_eguangtong?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

server:
   port: 9081
eureka:
   instance:
       hostname: localhost
   client:
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:8761/eureka/
